Vagrant.configure("2") do |config|
  config.vm.box = "kwilczynski/ubuntu-20.04-docker"
  config.vm.box_version = "0.1.1"

  # config.vm.box = "gusztavvargadr/docker-linux"
  # config.vm.box_version = "2600.2404.2409"

  # Cấu hình cho manager1
  config.vm.define "manager1" do |manager|
    manager.vm.hostname = "manager1"
    manager.vm.network "private_network", ip: "192.168.56.11"
    manager.vm.synced_folder "./synced_folder", "/home/vagrant"
    manager.vm.network "forwarded_port", guest: 9000, host: 9000

    manager.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y sshpass
    SHELL
  end
  
  # Cấu hình cho manager2
  config.vm.define "manager2" do |manager|
    manager.vm.hostname = "manager2"
    manager.vm.network "private_network", ip: "192.168.56.12"
  end

  # Cấu hình cho manager3
  config.vm.define "manager3" do |manager|
    manager.vm.hostname = "manager3"
    manager.vm.network "private_network", ip: "192.168.56.13"
  end

  # Cấu hình cho worker1
  config.vm.define "worker1" do |worker|
    worker.vm.hostname = "worker1"
    worker.vm.network "private_network", ip: "192.168.56.21"
  end

  # Cấu hình cho worker2
  config.vm.define "worker2" do |worker|
    worker.vm.hostname = "worker2"
    worker.vm.network "private_network", ip: "192.168.56.22"
  end

  # Cấu hình cho worker3
  config.vm.define "worker3" do |worker|
    worker.vm.hostname = "worker3"
    worker.vm.network "private_network", ip: "192.168.56.23"
  end

  # Cấu hình cho worker4
  config.vm.define "worker4" do |worker|
    worker.vm.hostname = "worker4"
    worker.vm.network "private_network", ip: "192.168.56.24"
  end

  # Cấu hình cho worker5
  config.vm.define "worker5" do |worker|
    worker.vm.hostname = "worker5"
    worker.vm.network "private_network", ip: "192.168.56.25"
  end
end